server:
  app_version: 0.0.1
  address: localhost:8513
  port: 8513
  log_level: debug

postgres:
  host: localhost
  port: 5432
  user: root
  password: root
  db_name: shortify
  log_level: error

redis:
  address: localhost:6379
  password:

shortener:
  code_length: 5

worker_pool:
  worker_count: 10
  queue_size: 5

telemetry:
  service_namespace_key: shortify_namespace
  service_name_key: shortify
  trace:
    enabled: true
    jaeger_host: localhost
    jaeger_port: 6831
  metric:
    enabled: true
    address: :8080
