apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortify
  labels:
    app: shortify
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels:
      app: shortify
  template:
    metadata:
      labels:
        app: shortify
    spec:
      volumes:
        - name: volmap
          configMap:
            name: shortify-config
      containers:
        - name: shortify
          image: mimbe/shortify
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /app/config.yml
              name: volmap
          resources:
            limits:
              cpu: "0.2"
              memory: 128Mi
